//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.8
//
// <auto-generated>
//
// Generated from file `Parking.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package ParkingDemo;

public interface TotalPayablePrx extends com.zeroc.Ice.ObjectPrx
{
    default double payable(double hours)
    {
        return payable(hours, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default double payable(double hours, java.util.Map<String, String> context)
    {
        return _iceI_payableAsync(hours, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> payableAsync(double hours)
    {
        return _iceI_payableAsync(hours, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> payableAsync(double hours, java.util.Map<String, String> context)
    {
        return _iceI_payableAsync(hours, context, false);
    }

    /**
     * @hidden
     * @param iceP_hours -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> _iceI_payableAsync(double iceP_hours, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "payable", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeDouble(iceP_hours);
                 }, istr -> {
                     double ret;
                     ret = istr.readDouble();
                     return ret;
                 });
        return f;
    }

    default double getValueHours()
    {
        return getValueHours(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default double getValueHours(java.util.Map<String, String> context)
    {
        return _iceI_getValueHoursAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> getValueHoursAsync()
    {
        return _iceI_getValueHoursAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> getValueHoursAsync(java.util.Map<String, String> context)
    {
        return _iceI_getValueHoursAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> _iceI_getValueHoursAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getValueHours", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     double ret;
                     ret = istr.readDouble();
                     return ret;
                 });
        return f;
    }

    default double calculateHours(String enter)
    {
        return calculateHours(enter, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default double calculateHours(String enter, java.util.Map<String, String> context)
    {
        return _iceI_calculateHoursAsync(enter, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> calculateHoursAsync(String enter)
    {
        return _iceI_calculateHoursAsync(enter, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Double> calculateHoursAsync(String enter, java.util.Map<String, String> context)
    {
        return _iceI_calculateHoursAsync(enter, context, false);
    }

    /**
     * @hidden
     * @param iceP_enter -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> _iceI_calculateHoursAsync(String iceP_enter, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Double> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "calculateHours", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_enter);
                 }, istr -> {
                     double ret;
                     ret = istr.readDouble();
                     return ret;
                 });
        return f;
    }

    default String getEnterDate(String licensePlate)
    {
        return getEnterDate(licensePlate, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getEnterDate(String licensePlate, java.util.Map<String, String> context)
    {
        return _iceI_getEnterDateAsync(licensePlate, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getEnterDateAsync(String licensePlate)
    {
        return _iceI_getEnterDateAsync(licensePlate, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getEnterDateAsync(String licensePlate, java.util.Map<String, String> context)
    {
        return _iceI_getEnterDateAsync(licensePlate, context, false);
    }

    /**
     * @hidden
     * @param iceP_licensePlate -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getEnterDateAsync(String iceP_licensePlate, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getEnterDate", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_licensePlate);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TotalPayablePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), TotalPayablePrx.class, _TotalPayablePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TotalPayablePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), TotalPayablePrx.class, _TotalPayablePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TotalPayablePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), TotalPayablePrx.class, _TotalPayablePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TotalPayablePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), TotalPayablePrx.class, _TotalPayablePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static TotalPayablePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, TotalPayablePrx.class, _TotalPayablePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static TotalPayablePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, TotalPayablePrx.class, _TotalPayablePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default TotalPayablePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (TotalPayablePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default TotalPayablePrx ice_adapterId(String newAdapterId)
    {
        return (TotalPayablePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default TotalPayablePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (TotalPayablePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default TotalPayablePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (TotalPayablePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default TotalPayablePrx ice_invocationTimeout(int newTimeout)
    {
        return (TotalPayablePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default TotalPayablePrx ice_connectionCached(boolean newCache)
    {
        return (TotalPayablePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default TotalPayablePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (TotalPayablePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TotalPayablePrx ice_secure(boolean b)
    {
        return (TotalPayablePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default TotalPayablePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (TotalPayablePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TotalPayablePrx ice_preferSecure(boolean b)
    {
        return (TotalPayablePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default TotalPayablePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (TotalPayablePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default TotalPayablePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (TotalPayablePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default TotalPayablePrx ice_collocationOptimized(boolean b)
    {
        return (TotalPayablePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default TotalPayablePrx ice_twoway()
    {
        return (TotalPayablePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default TotalPayablePrx ice_oneway()
    {
        return (TotalPayablePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default TotalPayablePrx ice_batchOneway()
    {
        return (TotalPayablePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default TotalPayablePrx ice_datagram()
    {
        return (TotalPayablePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default TotalPayablePrx ice_batchDatagram()
    {
        return (TotalPayablePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default TotalPayablePrx ice_compress(boolean co)
    {
        return (TotalPayablePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default TotalPayablePrx ice_timeout(int t)
    {
        return (TotalPayablePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default TotalPayablePrx ice_connectionId(String connectionId)
    {
        return (TotalPayablePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default TotalPayablePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (TotalPayablePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::ParkingDemo::TotalPayable";
    }
}
